[package]
name = "leology"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
rand = "0.8.5"
snarkvm = "0.16.8"
snarkvm-console = "0.16.6"
anyhow = "1.0.75"
rand_chacha = "0.3.1"
snarkos-account = "2.2.4"
reqwest = "0.11.22"
serde_json = "1.0.108"
