// This file will be autogenerated in the future.
use leology::*;

generate_bindings!(
    Token, {
        mint_private, (to: Address<Testnet3>, amount: u64),
        Result<(Response<Testnet3>, Transaction<Testnet3>)>
    }
);